# Generated by Django 5.2.8 on 2025-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "productivity",
            "0002_alter_document_options_document_tags_milestone_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="goal",
            options={
                "ordering": ["target_date", "-progress", "-created_at"],
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
            },
        ),
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["-current_streak", "name"],
                "verbose_name": "Habit",
                "verbose_name_plural": "Habits",
            },
        ),
        migrations.AlterModelOptions(
            name="milestone",
            options={
                "ordering": ["due_date", "created_at"],
                "verbose_name": "Milestone",
                "verbose_name_plural": "Milestones",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["due_date", "-priority", "-created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="timetable",
            options={
                "ordering": ["-active", "-updated_at"],
                "verbose_name": "Timetable",
                "verbose_name_plural": "Timetables",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AddField(
            model_name="goal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
