# Generated by Django 5.2.8 on 2026-01-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image for the blog post",
                null=True,
                upload_to="blog/",
            ),
        ),
    ]
