# Generated by Django 5.2.8 on 2025-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at", "name"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="flashcard",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Flashcard",
                "verbose_name_plural": "Flashcards",
            },
        ),
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-updated_at", "-created_at"],
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
            },
        ),
        migrations.AlterModelOptions(
            name="studysession",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Study Session",
                "verbose_name_plural": "Study Sessions",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
