# Generated by Django 5.2.8 on 2025-12-09 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessidea",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Business Idea",
                "verbose_name_plural": "Business Ideas",
            },
        ),
        migrations.AlterModelOptions(
            name="businessplan",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Business Plan",
                "verbose_name_plural": "Business Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="importexportrecord",
            options={
                "ordering": ["-date"],
                "verbose_name": "Import/Export Record",
                "verbose_name_plural": "Import/Export Records",
            },
        ),
        migrations.AlterModelOptions(
            name="marketresearch",
            options={
                "ordering": ["-date"],
                "verbose_name": "Market Research",
                "verbose_name_plural": "Market Research",
            },
        ),
    ]
