# Generated by Django 5.2.8 on 2025-12-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_project_projectimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cv_file",
            field=models.FileField(
                blank=True,
                help_text="Upload CV/Resume PDF",
                null=True,
                upload_to="profile/cv/",
            ),
        ),
    ]
