# Generated by Django 5.2.8 on 2025-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_profile_cv_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="projectimage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project Image",
                "verbose_name_plural": "Project Images",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
