# Generated by Django 5.2.8 on 2025-12-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_alter_profile_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Main cover image",
                null=True,
                upload_to="projects/",
            ),
        ),
    ]
